src/CursoInicianteMvc/Models/Pessoa.cs
namespace CursoInicianteMvc.Models;

public class Pessoa
{
    public Guid Id { get; set; }
    public required string Nome { get; set; }
    public required string Email { get; set; }
    public string? Celular { get; set; }

    public ICollection<Tarefa> Tarefas { get; set; }
}

public class Tarefa
{
    public Guid Id { get; set; }
    public Guid PessoaId { get; set; }
    public required string Descricao { get; set; }
    
    public DateTime? RealizadoEm { get; set; }

    public Pessoa Pessoa { get; set; }
}

src/CursoInicianteMvc/Controllers/PessoaController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CursoInicianteMvc.Models;
using CursoInicianteMvc.Services;

namespace CursoInicianteMvc.Controllers
{
    public class PessoaController : CursoControllerBase
    {
        private readonly IPessoaService _pessoaService;

        public PessoaController(IPessoaService pessoaService) =>
            _pessoaService = pessoaService;

        [HttpGet]
        public ViewResult Index() => View();

        [HttpGet]
        public async Task<JsonResult> Search(Filter filtro)
        {
            var resultado = await _pessoaService.Search(filtro);
            return new JsonResult(new { total = resultado.Item1, rows = resultado.Item2 });
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid? id)
        {
            var pessoa = await _pessoaService.Find(id.GetValueOrDefault());
            if (pessoa == null) return RedirectToAction("NaoEncontrado");
            return View(pessoa);
        }

        [HttpGet]
        public ViewResult Create() => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PessoaCadastrarViewModel pessoa)
        {
            if (!ModelState.IsValid) return View(pessoa);
            var id = await _pessoaService.Create(pessoa);
            return RedirectToAction(nameof(Details), new { id });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid? id)
        {
            var pessoa = await _pessoaService.Find(id.GetValueOrDefault());
            if (pessoa == null) return RedirectToAction("NaoEncontrado");
            return View(pessoa);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(PessoaEditarViewModel pessoa)
        {
            if (!ModelState.IsValid) return View(pessoa);
            await _pessoaService.Edit(pessoa);
            return RedirectToAction(nameof(Details), new { pessoa.Id });
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid? id)
        {
            var pessoa = await _pessoaService.Find(id.GetValueOrDefault());
            if (pessoa == null) return RedirectToAction("NaoEncontrado");
            return View(pessoa);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await _pessoaService.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

src/CursoInicianteMvc/Controllers/TarefaController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CursoInicianteMvc.Models;
using CursoInicianteMvc.Services;

namespace CursoInicianteMvc.Controllers
{
    public class TarefaController : CursoControllerBase
    {
        private readonly ITarefaService _tarefaService;

        public TarefaController(ITarefaService tarefaService) =>
            _tarefaService = tarefaService;

        [HttpGet]
        public async Task<JsonResult> Search(TarefaFilter filtro)
        {
            var result = await _tarefaService.Search(filtro);
            return new JsonResult(new { rows = result.Item2, total = result.Item1 });
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid? id)
        {
            var tarefa = await _tarefaService.FindDetails(id.GetValueOrDefault());
            if (tarefa == null) return NaoEncontrado();
            return View(tarefa);
        }

        [HttpGet]
        public async Task<IActionResult> Create(Guid pessoaId)
        {
            var tarefa = await _tarefaService.FindCreate(pessoaId);
            return tarefa == null
                ? NaoEncontrado()
                : View(tarefa);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TarefaCadastrarViewModel tarefa)
        {
            if (!ModelState.IsValid)
            {
                tarefa = (await _tarefaService.FindCreate(tarefa.PessoaId))!;
                return View(tarefa);
            }

            await _tarefaService.Create(tarefa);
            return RedirectToAction(nameof(Details), "Pessoa", new { Id = tarefa.PessoaId });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid? id)
        {
            var tarefa = await _tarefaService.FindEdit(id.GetValueOrDefault());
            if (tarefa == null) return NaoEncontrado();
            return View(tarefa);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(TarefaEditarViewModel tarefa)
        {
            if (!ModelState.IsValid)
            {
                tarefa = (await _tarefaService.FindEdit(tarefa.Id))!;
                return View(tarefa);
            }

            await _tarefaService.Edit(tarefa);

            return RedirectToAction(nameof(Details), new { tarefa.Id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<RedirectToActionResult> Finish(Guid? id)
        {
            await _tarefaService.Finish(id.GetValueOrDefault());
            return RedirectToAction(nameof(Details), new { id });
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid? id)
        {
            var tarefa = await _tarefaService.FindDetails(id.GetValueOrDefault());
            if (tarefa == null) return NaoEncontrado();
            return View(tarefa);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var tarefa = await _tarefaService.FindDetails(id);
            await _tarefaService.Delete(id);
            return RedirectToAction(nameof(Details), "Pessoa", new { Id = tarefa.PessoaId });
        }
    }
}

src/CursoInicianteMvc/Views/Pessoa/Create.cshtml
@model CursoInicianteMvc.Models.PessoaCadastrarViewModel

@{
    ViewData["Title"] = "Nova Pessoa";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Scripts {@{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

<div class="row">
    <div class="col-12">
        <div class="card">
            <form asp-action="Create" asp-controller="Pessoa" method="post">
                <div class="card-header d-flex pt-3">
                    <div class="card-title">
                        <h4>Nova Pessoa</h4>
                    </div>
                </div>
                <div class="card-body">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label asp-for="Nome" class="form-label"></label>
                                <input asp-for="Nome" class="form-control"/>
                                <span asp-validation-for="Nome" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label asp-for="Email" class="form-label"></label>
                                <input asp-for="Email" class="form-control"/>
                                <span asp-validation-for="Email" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label asp-for="Celular" class="form-label"></label>
                                <input asp-for="Celular" class="form-control"/>
                                <span asp-validation-for="Celular" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer d-flex">
                    <div>
                        <a class="btn btn-secondary" asp-action="Index" asp-controller="Pessoa">Voltar</a>
                    </div>
                    <div class="ms-auto">
                        <button type="submit" class="btn btn-primary">Salvar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

src/CursoInicianteMvc/Views/Pessoa/Delete.cshtml
@model CursoInicianteMvc.Models.PessoaEditarViewModel
@{
    ViewData["Title"] = "Excluir Pessoa";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Styles{ <link rel="stylesheet" href="~/lib/bootstrap-table/dist/bootstrap-table.min.css"> }

@section Scripts
{
    <script type="text/javascript" src="~/lib/bootstrap-table/dist/bootstrap-table.min.js"></script>
    <script type="text/javascript" src="~/lib/bootstrap-table/dist/locale/bootstrap-table-pt-BR.min.js"></script>
    <script type="text/javascript" src="~/js/pessoa.details.js"></script>    
}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header d-flex pt-3">
                <div class="card-title">
                    <h4>Excluir: @Model.Nome</h4>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col">
                        <div class="form-group">
                            <label asp-for="Nome" class="form-label"></label>
                            <input asp-for="Nome" class="form-control" readonly="readonly"/>
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <label asp-for="Email" class="form-label"></label>
                            <input asp-for="Email" class="form-control" readonly="readonly"/>
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <label asp-for="Celular" class="form-label"></label>
                            <input asp-for="Celular" class="form-control" readonly="readonly"/>
                        </div>
                    </div>
                </div>

            </div>
            <div class="card-body">
                <h5 class="text-danger">As tarefas e subtarefas relacionadas serão excluídas junto com a pessoa.</h5>
                <table
                    class="table"
                    data-toggle="table"
                    data-url="@Url.Action("Search", "Tarefa", new { pessoaId = Model.Id })"
                    data-pagination="true"
                    data-side-pagination="server"
                    data-locale="pt-BR">
                    <thead>
                    <th data-title="Descrição" data-field="descricao" data-sortable="true" data-sort-name="Descricao"></th>
                    <th data-title="Realizado Em" data-field="realizadoEm" data-sortable="true" data-sort-name="RealizadoEm" data-formatter="formatarData"></th>
                    <th data-title="Qnt. Sub-Tarefas" data-field="qntSubtarefas" data-sortable="false" data-align="center"></th>
                    <th data-title="Qnt. Sub-Tarefas Realizadas" data-field="qntSubtarefasConcluidas" data-sortable="false" data-align="center"></th>
                    </thead>
                </table>
            </div>
            <div class="card-footer d-flex">
                <a asp-action="Details" asp-route-id="@Model.Id" class="btn btn-secondary">Voltar</a>
                <div class="ms-auto">
                    <form asp-action="Delete">
                        <input type="hidden" asp-for="Id"/>
                        <button class="btn btn-danger">Excluir</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

src/CursoInicianteMvc/Views/Pessoa/Details.cshtml
@model CursoInicianteMvc.Models.PessoaEditarViewModel

@{
    ViewData["Title"] = "Detalhes de Pessoa";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Styles{ <link rel="stylesheet" href="~/lib/bootstrap-table/dist/bootstrap-table.min.css"> }

@section Scripts
{
    <script type="text/javascript" src="~/lib/bootstrap-table/dist/bootstrap-table.min.js"></script>
    <script type="text/javascript" src="~/lib/bootstrap-table/dist/locale/bootstrap-table-pt-BR.min.js"></script>
    <script type="text/javascript" src="~/js/pessoa.details.js" asp-append-version="true"></script>
}

<input type="hidden" id="url-tarefa-editar" value="@Url.Action("Edit", "Tarefa")">
<input type="hidden" id="url-tarefa-detalhes" value="@Url.Action("Details", "Tarefa")">
<input type="hidden" id="url-tarefa-excluir" value="@Url.Action("Delete", "Tarefa")">

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header d-flex pt-3">
                <div class="card-title flex-grow-1">
                    <h4>Detalhes da Pessoa</h4>
                </div>
                <div class="mx-1">
                    <a asp-action="Delete" asp-controller="Pessoa" asp-route-id="@Model?.Id" class="btn btn-danger">Excluir</a>
                </div>
                <div class="mx-1">
                    <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-primary">Editar</a>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col">
                        <div class="form-group">
                            <label asp-for="Nome" class="form-label"></label>
                            <input asp-for="Nome" class="form-control" readonly="readonly"/>
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <label asp-for="Email" class="form-label"></label>
                            <input asp-for="Email" class="form-control" readonly="readonly"/>
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <label asp-for="Celular" class="form-label"></label>
                            <input asp-for="Celular" class="form-control" readonly="readonly"/>
                        </div>
                    </div>
                </div>

            </div>
            <div class="card-body">
                <table
                    class="table"
                    data-toggle="table"
                    data-url="@Url.Action("Search", "Tarefa", new { pessoaId = Model.Id })"
                    data-pagination="true"
                    data-side-pagination="server"
                    data-locale="pt-BR"
                    data-search="true">
                    <thead>
                    <th data-title="Descrição" data-field="descricao" data-sortable="true" data-sort-name="Descricao"></th>
                    <th data-title="Realizado Em" data-field="realizadoEm" data-sortable="true" data-sort-name="RealizadoEm" data-formatter="formatarData"></th>
                    <th data-title="Qnt. Sub-Tarefas" data-field="qntSubtarefas" data-sortable="false" data-align="center"></th>
                    <th data-title="Qnt. Sub-Tarefas Realizadas" data-field="qntSubtarefasConcluidas" data-sortable="false" data-align="center"></th>
                    <th data-title="#" data-field="id" data-formatter="btnAcoes" data-align="center"></th>
                    </thead>
                </table>
            </div>
            <div class="card-footer d-flex">
                <a asp-action="Index" class="btn btn-secondary">Voltar</a>
                <a asp-controller="Tarefa" asp-action="Create" asp-route-pessoaId="@Model.Id" class="btn btn-info ms-auto">Adicionar Tarefa</a>
            </div>
        </div>
    </div>
</div>

src/CursoInicianteMvc/Views/Pessoa/Edit.cshtml
@model CursoInicianteMvc.Models.PessoaEditarViewModel

@{
    ViewData["Title"] = "Editar Pessoa";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

<div class="row">
    <div class="col-12">
        <div class="card">
                <form asp-action="Edit" asp-controller="Pessoa" method="post">
                    <div class="card-header d-flex pt-3">
                        <div class="card-title">
                            <h4>Editar Pessoa</h4>
                        </div>
                    </div>
                    <div class="card-body">
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <input asp-for="Id" type="hidden">
                        <div class="row">
                            <div class="col">
                                <div class="form-group">
                                    <label asp-for="Nome" class="form-label"></label>
                                    <input asp-for="Nome" class="form-control"/>
                                    <span asp-validation-for="Nome" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group">
                                    <label asp-for="Email" class="form-label"></label>
                                    <input asp-for="Email" class="form-control"/>
                                    <span asp-validation-for="Email" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group">
                                    <label asp-for="Celular" class="form-label"></label>
                                    <input asp-for="Celular" class="form-control"/>
                                    <span asp-validation-for="Celular" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer d-flex">
                        <div>
                            <a class="btn btn-secondary" asp-action="Details" asp-controller="Pessoa" asp-route-id="@Model.Id">Voltar</a>
                        </div>
                        <div class="ms-auto">
                            <button type="submit" class="btn btn-primary">Salvar</button>
                        </div>
                    </div>
                </form>
            </div>
    </div>
</div>

src/CursoInicianteMvc/Views/Pessoa/Index.cshtml
@{
    ViewData["Title"] = "Pessoas Cadastradas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Styles { <link rel="stylesheet" href="~/lib/bootstrap-table/dist/bootstrap-table.min.css"> }

@section Scripts
{
    <script type="text/javascript" src="~/lib/bootstrap-table/dist/bootstrap-table.min.js"></script>
    <script type="text/javascript" src="~/lib/bootstrap-table/dist/locale/bootstrap-table-pt-BR.min.js"></script>
    <script type="text/javascript" src="~/js/pessoa.index.js" asp-append-version="true"></script>
}

<input type="hidden" id="url-detalhes" value="@Url.Action("Details")">

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header d-flex pt-3">
                <div class="card-title">
                    <h4>Pessoas</h4>
                </div>
                <div class="ms-auto">
                    <a asp-action="Create" class="btn btn-primary">Nova</a>
                </div>
            </div>
            <div class="card-body">
                <table
                    class="table"
                    data-toggle="table"
                    data-url="@Url.Action("Search")"
                    data-pagination="true"
                    data-side-pagination="server"
                    data-locale="pt-BR"
                    data-search="true">
                    <thead>
                    <th data-title="Nome" data-field="nome" data-sortable="true" data-sort-name="Nome" data-width="20" data-width-unit="%"></th>
                    <th data-title="e-Mail" data-field="email" data-sortable="true" data-sort-name="Email" data-width="20" data-width-unit="%"></th>
                    <th data-title="Celular" data-field="celular" data-sortable="true" data-sort-name="Celular"></th>
                    <th data-title="Qnt. Tarefas" data-field="qntTarefas" data-sortable="false" data-align="center"></th>
                    <th data-title="Qnt. Sub-Tarefas" data-field="qntSubtarefas" data-sortable="false" data-align="center"></th>
                    <th data-title="#" data-field="id" data-formatter="btnAcoes" data-align="center"></th>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>