src/CursoInicianteMvc/Controllers/PessoaController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CursoInicianteMvc.Models;
using CursoInicianteMvc.Services;

namespace CursoInicianteMvc.Controllers
{
    public class PessoaController : CursoControllerBase
    {
        private readonly IPessoaService _pessoaService;

        public PessoaController(IPessoaService pessoaService) =>
            _pessoaService = pessoaService;

        [HttpGet]
        public ViewResult Index() => View();

        [HttpGet]
        public async Task<JsonResult> Search(Filter filtro)
        {
            var resultado = await _pessoaService.Search(filtro);
            return new JsonResult(new { total = resultado.Item1, rows = resultado.Item2 });
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid? id)
        {
            var pessoa = await _pessoaService.Find(id.GetValueOrDefault());
            if (pessoa == null) return RedirectToAction("NaoEncontrado");
            return View(pessoa);
        }

        [HttpGet]
        public ViewResult Create() => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PessoaCadastrarViewModel pessoa)
        {
            if (!ModelState.IsValid) return View(pessoa);
            var id = await _pessoaService.Create(pessoa);
            return RedirectToAction(nameof(Details), new { id });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid? id)
        {
            var pessoa = await _pessoaService.Find(id.GetValueOrDefault());
            if (pessoa == null) return RedirectToAction("NaoEncontrado");
            return View(pessoa);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(PessoaEditarViewModel pessoa)
        {
            if (!ModelState.IsValid) return View(pessoa);
            await _pessoaService.Edit(pessoa);
            return RedirectToAction(nameof(Details), new { pessoa.Id });
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid? id)
        {
            var pessoa = await _pessoaService.Find(id.GetValueOrDefault());
            if (pessoa == null) return RedirectToAction("NaoEncontrado");
            return View(pessoa);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await _pessoaService.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

src/CursoInicianteMvc/Controllers/SubtarefaController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CursoInicianteMvc.Models;
using CursoInicianteMvc.Services;

namespace CursoInicianteMvc.Controllers
{
    public class SubtarefaController : CursoControllerBase
    {
        private readonly ISubtarefaService _subtarefaService;

        public SubtarefaController(ISubtarefaService subtarefaService) =>
            _subtarefaService = subtarefaService;

        [HttpGet]
        public async Task<JsonResult> Search(SubtarefaFilter filtro)
        {
            var resultado = await _subtarefaService.Search(filtro);
            return new JsonResult(new { rows = resultado.Item2, total = resultado.Item1 });
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid? id)
        {
            var subtarefa = await _subtarefaService.FindDetails(id.GetValueOrDefault());
            if (subtarefa == null) return NaoEncontrado();
            return View(subtarefa);
        }

        [HttpGet]
        public async Task<IActionResult> Create(Guid tarefaId) =>
            View(await _subtarefaService.FindCreate(tarefaId));

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SubtarefaCadastrarViewModel subtarefa)
        {
            if (!ModelState.IsValid) return View(await _subtarefaService.FindCreate(subtarefa.TarefaId));
            var id = await _subtarefaService.Create(subtarefa);
            return RedirectToAction(nameof(Details), new { id });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid? id)
        {
            var subtarefa = await _subtarefaService.FindEdit(id.GetValueOrDefault());
            if (subtarefa == null) return NaoEncontrado();
            return View(subtarefa);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(SubtarefaEditarViewModel subtarefa)
        {
            if (!ModelState.IsValid) return View(await _subtarefaService.FindEdit(subtarefa.Id));
            await _subtarefaService.Edit(subtarefa);
            return RedirectToAction(nameof(Details), new { subtarefa.Id });
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid? id)
        {
            var subtarefa = await _subtarefaService.FindDetails(id.GetValueOrDefault());
            if (subtarefa == null) return NaoEncontrado();
            return View(subtarefa);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var subtarefa = await _subtarefaService.FindDetails(id);
            await _subtarefaService.Delete(id);
            return RedirectToAction("Details", "Tarefa", new { Id = subtarefa.TarefaId });
        }


        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Finish(Guid id)
        {
            await _subtarefaService.Finish(id);
            return RedirectToAction("Details", new { id });
        }
    }
}

src/CursoInicianteMvc/Controllers/TarefaController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CursoInicianteMvc.Models;
using CursoInicianteMvc.Services;

namespace CursoInicianteMvc.Controllers
{
    public class TarefaController : CursoControllerBase
    {
        private readonly ITarefaService _tarefaService;

        public TarefaController(ITarefaService tarefaService) =>
            _tarefaService = tarefaService;

        [HttpGet]
        public async Task<JsonResult> Search(TarefaFilter filtro)
        {
            var result = await _tarefaService.Search(filtro);
            return new JsonResult(new { rows = result.Item2, total = result.Item1 });
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid? id)
        {
            var tarefa = await _tarefaService.FindDetails(id.GetValueOrDefault());
            if (tarefa == null) return NaoEncontrado();
            return View(tarefa);
        }

        [HttpGet]
        public async Task<IActionResult> Create(Guid pessoaId)
        {
            var tarefa = await _tarefaService.FindCreate(pessoaId);
            return tarefa == null
                ? NaoEncontrado()
                : View(tarefa);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TarefaCadastrarViewModel tarefa)
        {
            if (!ModelState.IsValid)
            {
                tarefa = (await _tarefaService.FindCreate(tarefa.PessoaId))!;
                return View(tarefa);
            }

            await _tarefaService.Create(tarefa);
            return RedirectToAction(nameof(Details), "Pessoa", new { Id = tarefa.PessoaId });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid? id)
        {
            var tarefa = await _tarefaService.FindEdit(id.GetValueOrDefault());
            if (tarefa == null) return NaoEncontrado();
            return View(tarefa);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(TarefaEditarViewModel tarefa)
        {
            if (!ModelState.IsValid)
            {
                tarefa = (await _tarefaService.FindEdit(tarefa.Id))!;
                return View(tarefa);
            }

            await _tarefaService.Edit(tarefa);

            return RedirectToAction(nameof(Details), new { tarefa.Id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<RedirectToActionResult> Finish(Guid? id)
        {
            await _tarefaService.Finish(id.GetValueOrDefault());
            return RedirectToAction(nameof(Details), new { id });
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid? id)
        {
            var tarefa = await _tarefaService.FindDetails(id.GetValueOrDefault());
            if (tarefa == null) return NaoEncontrado();
            return View(tarefa);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var tarefa = await _tarefaService.FindDetails(id);
            await _tarefaService.Delete(id);
            return RedirectToAction(nameof(Details), "Pessoa", new { Id = tarefa.PessoaId });
        }
    }
}

src/CursoInicianteMvc/Views/Tarefa/Create.cshtml
@model CursoInicianteMvc.Models.TarefaCadastrarViewModel

@{
    ViewData["Title"] = "Nova Tarefa";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

<div class="row">
    <div class="col-12">
        <div class="card">
            <form asp-action="Create" method="post">
                <div class="card-header d-flex pt-3">
                    <div class="card-title">
                        <h4>Nova Tarefa</h4>
                    </div>
                </div>
                <div class="card-body">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <input type="hidden" asp-for="@Model.PessoaId">
                    <div class="row gap-3">
                        <div class="col-12">
                            <div class="form-group">
                                <label asp-for="PessoaId" class="form-label"></label>
                                <input asp-for="PessoaNome" readonly="readonly" disabled="disabled" class="form-control">
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                <label asp-for="Descricao" class="form-label"></label>
                                <textarea asp-for="Descricao" class="form-control"></textarea>
                                <span asp-validation-for="Descricao" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer d-flex">
                    <div>
                        <a class="btn btn-secondary" asp-controller="Pessoa" asp-action="Details" asp-route-id="@Model.PessoaId">Voltar</a>
                    </div>
                    <div class="ms-auto">
                        <button type="submit" class="btn btn-primary">Cadastrar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

src/CursoInicianteMvc/Views/Tarefa/Delete.cshtml
@model CursoInicianteMvc.Models.TarefaDetalharViewModel

@{
    ViewData["Title"] = "Excluir Tarefa";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Styles{ <link rel="stylesheet" href="~/lib/bootstrap-table/dist/bootstrap-table.min.css"> }

@section Scripts
{
    <script type="text/javascript" src="~/lib/bootstrap-table/dist/bootstrap-table.min.js"></script>
    <script type="text/javascript" src="~/lib/bootstrap-table/dist/locale/bootstrap-table-pt-BR.min.js"></script>
    <script type="text/javascript" src="~/js/tarefa.details.js" asp-append-version="true"></script>
}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header d-flex py-3">
                <div class="card-title flex-grow-1">
                    <h4>Excluir Tarefa: @Model.Descricao</h4>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col">
                        <div class="form-group">
                            <label asp-for="PessoaId" class="form-label"></label>
                            <input asp-for="PessoaNome" class="form-control-plaintext" readonly="readonly"/>
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <label asp-for="RealizadoEm" class="form-label"></label>
                            <input asp-for="RealizadoEm" class="form-control-plaintext" readonly="readonly"/>
                        </div>
                    </div>
                </div>

            </div>
            <div class="card-body">
                <h5 class="text-danger">As subtarefas serão excluídas juntamente com a tarefa</h5>
                @{@(await Html.PartialAsync("_Subtarefas", Model.Id))}
            </div>
            <div class="card-footer d-flex">
                <div>
                    <a asp-controller="Tarefa" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-secondary">Voltar</a>
                </div>
                @if (!Model.RealizadoEm.HasValue)
                {
                    <div class="ms-auto">
                        <form asp-action="Delete">
                            <input type="hidden" asp-for="Id"/>
                            <button class="btn btn-danger">Excluir</button>
                        </form>
                    </div>
                }
            </div>
        </div>
    </div>

</div>

src/CursoInicianteMvc/Views/Tarefa/Details.cshtml
@model CursoInicianteMvc.Models.TarefaDetalharViewModel

@{
    ViewData["Title"] = "Detalhes da Tarefa";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Styles{ <link rel="stylesheet" href="~/lib/bootstrap-table/dist/bootstrap-table.min.css"> }

@section Scripts
{
    <script type="text/javascript" src="~/lib/bootstrap-table/dist/bootstrap-table.min.js"></script>
    <script type="text/javascript" src="~/lib/bootstrap-table/dist/locale/bootstrap-table-pt-BR.min.js"></script>
    <script type="text/javascript" src="~/js/tarefa.details.js" asp-append-version="true"></script>
}

<input type="hidden" id="url-editar" value="@Url.Action("Edit", "Subtarefa")">
<input type="hidden" id="url-detalhes" value="@Url.Action("Details", "Subtarefa")">
<input type="hidden" id="url-excluir" value="@Url.Action("Delete", "Subtarefa")">


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header d-flex py-3">
                <div class="card-title flex-grow-1">
                    <h4>Detalhes da Tarefa: @Model.Descricao</h4>
                </div>
                @{
                    if (!Model.RealizadoEm.HasValue)
                    {
                        <div class="mx-1">
                            <a asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger">Excluir</a>
                        </div>
                        <div class="mx-1">
                            <form asp-controller="Tarefa" asp-action="Finish" method="post">
                                <button class="mx-1 btn btn-primary" value="@Model.Id" name="@nameof(Model.Id)">Concluir</button>
                            </form>
                        </div>
                        
                        <div class="mx-1">
                            <a asp-action="Edit" asp-route-id="@Model?.Id" class=" btn btn-primary">Editar</a>
                        </div>
                    }
                }
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col">
                        <div class="form-group">
                            <label asp-for="PessoaId" class="form-label"></label>
                            <input asp-for="PessoaNome" class="form-control-plaintext" readonly="readonly"/>
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <label asp-for="RealizadoEm" class="form-label"></label>
                            <input asp-for="RealizadoEm" class="form-control-plaintext" readonly="readonly"/>
                        </div>
                    </div>
                </div>

            </div>
            <div class="card-body">
                @{ @(await Html.PartialAsync("_Subtarefas", Model.Id))}
            </div>
            <div class="card-footer d-flex">
                <div><a asp-controller="Pessoa" asp-action="Details" asp-route-id="@Model.PessoaId" class="btn btn-secondary">Voltar</a></div>
                @if (!Model.RealizadoEm.HasValue)
                {
                    <div class="ms-auto"><a asp-controller="Subtarefa" asp-action="Create" asp-route-tarefaId="@Model?.Id" class="mx-1 btn btn-info">Nova Sub-Tarefa</a></div>
                }
            </div>
        </div>
    </div>

</div>

src/CursoInicianteMvc/Views/Tarefa/Edit.cshtml
@model CursoInicianteMvc.Models.TarefaEditarViewModel

@{
    ViewData["Title"] = "Editar Tarefa";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-12">
        <div class="card">
                <form asp-action="Edit" asp-controller="Tarefa" method="post">
                    <div class="card-header py-3">
                        <div class="card-title">
                            <h4>Editar Tarefa</h4>
                        </div>
                    </div>
                    <div class="card-body">
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <input type="hidden" asp-for="@Model.Id">
                        <input type="hidden" asp-for="@Model.PessoaId">
                        <div class="row gap-3">
                            <div class="col-12">
                                <div class="form-group">
                                    <label asp-for="PessoaId" class="form-label"></label>
                                    <input class="form-control" asp-for="PessoaNome" disabled="disabled" readonly="readonly"/>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-group">
                                    <label asp-for="Descricao" class="form-label"></label>
                                    <textarea asp-for="Descricao" class="form-control"></textarea>
                                    <span asp-validation-for="Descricao" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer d-flex">
                        <div>
                            <a class="btn btn-secondary" asp-controller="Tarefa" asp-action="Details" asp-route-id="@Model.Id">Voltar</a>
                        </div>
                        <div class="ms-auto">
                            <button type="submit" class="btn btn-primary">Atualizar</button>
                        </div>
                    </div>
                </form>
            </div>
    </div>
</div>

src/CursoInicianteMvc/Views/Tarefa/_Subtarefas.cshtml
@model Guid

<table
    class="table"
    data-toggle="table"
    data-url="@Url.Action("Search", "Subtarefa", new { tarefaId = Model })"
    data-pagination="true"
    data-side-pagination="server"
    data-locale="pt-BR"
    data-search="true">
    <thead>
    <th data-title="Descrição" data-field="descricao" data-sortable="true" data-sort-name="Descricao"></th>
    <th data-title="Realizado Em" data-field="realizadoEm" data-sortable="true" data-sort-name="RealizadoEm" data-formatter="formatarData"></th>
    <th data-title="#" data-field="id" data-formatter="btnAcoes" data-align="center"></th>
    </thead>
</table>